apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediacenter.fullname" . }}-radarr
  labels:
    app: {{ template "mediacenter.name" . }}
    chart: {{ template "mediacenter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: radarr
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: {{ .Values.radarr.service.port }}
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: {{ template "mediacenter.name" . }}
    release: {{ .Release.Name }}
    component: radarr
