nzbget:
  ingress:
    enabled: true
    tls: 
    - hosts:
      - nzbget.k8s.lab.johnrowley.co
    hosts: 
    - nzbget.k8s.lab.johnrowley.co
  
  image:
    repository: linuxserver/nzbget
    tag: amd64-v21.0-r2302-ls9
    pullPolicy: IfNotPresent

  strategyType: Recreate

  nameOverride: ""
  fullnameOverride: ""

  timezone: UTC

  service:
    type: ClusterIP
    port: 6789
    annotations: {}
    labels: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  puid: 0
  pgid: 0

  volumes:
    - name: zdrive
      nfs:
        path: /mnt/slow/smb-shares/common/
        server: freenas.lab.johnrowley.co
    
    - name: nzbget
      iscsi:
        targetPortal: 192.168.100.15:3260
        portals: ['192.168.100.15:3260']
        iqn: iqn.2005-10.org.freenas.ctl:nzbget
        lun: 0
        fsType: ext4
        readOnly: false
  
  volumeMounts:
    - mountPath: /mnt/z/
      name: zdrive
    
    - mountPath: /mnt/nzbget
      name: nzbget
      subPath: data
    
    - mountPath: /config
      name: nzbget
      subPath: config

    - mountPath: /mnt/base-nzbget
      name: nzbget

radarr:
  ingress:
    enabled: true
    tls: 
    - hosts:
      - radarr.k8s.lab.johnrowley.co
    hosts: 
    - radarr.k8s.lab.johnrowley.co
    path: /

  replicaCount: 1

  image:
    repository: linuxserver/radarr
    tag: latest
    pullPolicy: IfNotPresent

  env:
    - name: PUID
      value: "0"
    - name: PGID
      value: "0"

  service:
    type: ClusterIP
    port: 80

  volumes:
    - name: zdrive
      nfs:
        path: /mnt/slow/smb-shares/common/
        server: freenas.lab.johnrowley.co
    
    - name: radarr
      iscsi:
        targetPortal: 192.168.100.15:3260
        portals: ['192.168.100.15:3260']
        iqn: iqn.2005-10.org.freenas.ctl:radarr
        lun: 0
        fsType: ext4
        readOnly: false

  volumeMounts:
    - name: radarr
      mountPath: "/config"
    - name: zdrive
      mountPath: "/mnt/z/"

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  nodeSelector: {}

  tolerations: []

  affinity: {}

lidarr:
  ingress:
    enabled: true
    tls: 
    - hosts:
      - lidarr.k8s.lab.johnrowley.co
    hosts: 
    - lidarr.k8s.lab.johnrowley.co
    path: /

  replicaCount: 1

  image:
    repository: linuxserver/lidarr
    tag: amd64-0.6.1.830-ls10
    pullPolicy: IfNotPresent

  env:
    - name: PUID
      value: "0"
    - name: PGID
      value: "0"

  service:
    type: ClusterIP
    port: 80

  volumes:
    - name: zdrive
      nfs:
        path: /mnt/slow/smb-shares/common/
        server: freenas.lab.johnrowley.co
    
    - name: lidarr
      iscsi:
        targetPortal: 192.168.100.15:3260
        portals: ['192.168.100.15:3260']
        iqn: iqn.2005-10.org.freenas.ctl:lidarr
        lun: 0
        fsType: ext4
        readOnly: false

  volumeMounts:
    - name: lidarr
      mountPath: "/config"
    - name: zdrive
      mountPath: "/mnt/z/"

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  nodeSelector: {}

  tolerations: []

  affinity: {}

sonarr:
  ingress:
    enabled: true
    tls: 
    - hosts:
      - sonarr.k8s.lab.johnrowley.co
    hosts: 
    - sonarr.k8s.lab.johnrowley.co
    path: /

  replicaCount: 1

  image:
    repository: linuxserver/sonarr
    tag: amd64-3.0.1.467-ls62
    pullPolicy: IfNotPresent

  env:
    - name: PUID
      value: "0"
    - name: PGID
      value: "0"

  service:
    type: ClusterIP
    port: 80

  volumes:
    - name: zdrive
      nfs:
        path: /mnt/slow/smb-shares/common/
        server: freenas.lab.johnrowley.co
    
    - name: sonarr
      iscsi:
        targetPortal: 192.168.100.15:3260
        portals: ['192.168.100.15:3260']
        iqn: iqn.2005-10.org.freenas.ctl:sonarr
        lun: 0
        fsType: ext4
        readOnly: false

  volumeMounts:
    - name: sonarr
      mountPath: "/config"
    - name: zdrive
      mountPath: "/mnt/z/"

  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
    limits:
      memory: 256Mi
      cpu: 0.5

  nodeSelector: {}

  tolerations: []

  affinity: {}