nzbget:
  ingress:
    enabled: true
    tls: 
    - hosts:
      - nzbget.k8s.lab.johnrowley.co
    hosts: 
    - nzbget.k8s.lab.johnrowley.co
  
  image:
    repository: linuxserver/nzbget
    tag: amd64-v21.0-r2302-ls9
    pullPolicy: IfNotPresent

  strategyType: Recreate

  nameOverride: ""
  fullnameOverride: ""

  timezone: UTC

  service:
    type: ClusterIP
    port: 6789
    annotations: {}
    labels: {}
    loadBalancerIP:

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  puid: 0
  pgid: 0

  volumes:
    - name: zdrive
      nfs:
        path: /mnt/slow/smb-shares/common/
        server: freenas.lab.johnrowley.co
    
    - name: nzbget
      iscsi:
        targetPortal: 192.168.100.15:3260
        portals: ['192.168.100.15:3260']
        iqn: iqn.2005-10.org.freenas.ctl:nzbget
        lun: 0
        fsType: ext4
        readOnly: false
  
  volumeMounts:
    - mountPath: /mnt/z/
      name: zdrive
    
    - mountPath: /mnt/nzbget
      name: nzbget
      subPath: data
    
    - mountPath: /config
      name: nzbget
      subPath: config

    - mountPath: /mnt/base-nzbget
      name: nzbget
radarr:
  ingress:
    enabled: true
    hosts: 
    - radarr.k8s.lab.johnrowley.co