# Default values for pgbouncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your includes.
replicaCount: 1


imagePullSecret: ''

image:
  repository: bitnami/pgbouncer
  tag: '1.20.1'
  pullPolicy: Always

antiAffinity: soft
additionalAffinities: {}

budget:
  minAvailable: 0

metrics:
  enabled: false
  serviceMonitor: 
    enabled: false
  image:
    repository: prometheuscommunity/pgbouncer-exporter
    tag: 'v0.7.0'
    pullPolicy: Always
  resources: {}

metricsEnvs: {}
  # DATABASE_URL: ...

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

service:
  name: pgbouncer
  type: ClusterIP
  externalPort: 6432
  internalPort: 6432

configEnvs: {}
  # DEBUG: ""

secretEnvs: 
  # -- Backend PostgreSQL username. Default: postgres.
  POSTGRESQL_USERNAME: "" 
  # -- Backend PostgreSQL password. No defaults.
  POSTGRESQL_PASSWORD: ""
  # -- Backend PostgreSQL Database name to connect to. Default: ${PGBOUNCER_DATABASE}.
  POSTGRESQL_DATABASE: ""
  # -- Backend PostgreSQL hostname. Default: postgresql.
  POSTGRESQL_HOST: ""
  # -- Backend PostgreSQL port. Default: 5432.
  POSTGRESQL_PORT: ""
  # -- Whether to include the backend PostgreSQL username in the database string. Default no.
  PGBOUNCER_SET_DATABASE_USER: ""
  # -- Whether to include the backend PostgreSQL password in the database string. Default no.
  PGBOUNCER_SET_DATABASE_PASSWORD: ""
  # -- Query which will be executed after a connection is established. No Defaults
  PGBOUNCER_CONNECT_QUERY: ""
  # -- The name of the database that pgbouncer should the backend as.
  PGBOUNCER_DATABASE: postgres
  # -- PgBouncer will use this user to connect to the database and query the PostgreSQL backend for a user and password. No defaults.
  PGBOUNCER_AUTH_USER: ""
  # -- PgBouncer will use this query to connect to the database and query the PostgreSQL backend for a user and password. No defaults.
  PGBOUNCER_AUTH_QUERY: ""
  # -- PgBouncer authentication type.
  PGBOUNCER_AUTH_TYPE: "scram-sha-256"
  # -- HBA configuration file to use if auth_type is set to hba. No defaults.
  PGBOUNCER_AUTH_HBA_FILE: ""
  # -- Specify content of the userlist.txt file
  PGBOUNCER_USERLIST: ""
  # -- PgBouncer pool mode. Allowed values: session, transaction and statement.
  PGBOUNCER_POOL_MODE: "session"
  # -- PgBouncer initialization sleep time. 
  PGBOUNCER_INIT_SLEEP_TIME: "10"
  # -- PgBouncer initialization maximum retries. Default: 10.
  PGBOUNCER_INIT_MAX_RETRIES: ""
  # -- PgBouncer maximum time queries are allowed to spend waiting for execution. Default: 120.
  PGBOUNCER_QUERY_WAIT_TIMEOUT: "120"
  # -- PgBouncer maximum number of client connections allowed.
  PGBOUNCER_MAX_CLIENT_CONN: "120"
  # -- PgBouncer maximum number of database connections allowed. A value of 0 indicates unlimited connections.
  PGBOUNCER_MAX_DB_CONNECTIONS : "0"
  # -- PgBouncer maximum time for a client to be in "idle in transaction" state. 
  PGBOUNCER_IDLE_TRANSACTION_TIMEOUT: "0.0"
  # -- PgBouncer maximum server connections to allow per user/database pair.
  PGBOUNCER_DEFAULT_POOL_SIZE: "20"
  # -- PgBouncer has at least this amount of open connections. A value of 0 indicates that there is no minimum pool size.
  PGBOUNCER_MIN_POOL_SIZE: "0"
  # -- PgBouncer allows this amount of additional connections. A value of 0 indicates that there is no reserve pool.
  PGBOUNCER_RESERVE_POOL_SIZE : "0"
  # -- you can use this to set ignore_startup_parameters in the auto-generated pgbouncer.ini. This can be useful for solving certain connection issues. See https://www.pgbouncer.org/ config.html for more details.
  PGBOUNCER_IGNORE_STARTUP_PARAMETERS: ""
  # -- PgBouncer maximum time in seconds a server connection can be idle. If 0 then the timeout is disabled. Default: 600
  PGBOUNCER_SERVER_IDLE_TIMEOUT: ""
  # -- PgBouncer query sent to server on connection release before making it available to other clients. Default: DISCARD ALL
  PGBOUNCER_SERVER_RESET_QUERY: "DISCARD ALL"
  # -- PgBouncer comma-separated list of database users that are allowed to connect and run read-only queries. No defaults.
  PGBOUNCER_STATS_USERS: ""